import { NextResponse } from 'next/server';
import { GoogleGenerativeAI } from '@google/generative-ai';

// File size limit (10MB)
const MAX_FILE_SIZE = 10 * 1024 * 1024;

export async function POST(request) {
  try {
    console.log('=== API Route Started ===');
    
    // Parse the form data
    const formData = await request.formData();
    const file = formData.get('file');
    const summaryLength = formData.get('summaryLength') || 'medium';
    const responseFormat = formData.get('format') || 'json';

    console.log('Form data parsed:', { 
      hasFile: !!file, 
      fileName: file?.name,
      fileSize: file?.size,
      fileType: file?.type,
      summaryLength,
      responseFormat
    });

    // Validate file input
    if (!file) {
      console.error('No file provided');
      return NextResponse.json({ error: 'No file provided' }, { status: 400 });
    }

    if (file.size > MAX_FILE_SIZE) {
      console.error('File too large:', file.size);
      return NextResponse.json({ error: 'File size exceeds 10MB limit' }, { status: 400 });
    }

    // Check supported file types
    const supportedTypes = [
      // Document types
      'application/pdf',
      'text/plain',
      'text/markdown',
      'application/msword',
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      // Image types
      'image/jpeg',
      'image/png', 
      'image/gif',
      'image/webp',
      'image/bmp',
      'image/svg+xml',
      // Other text types
      'application/rtf',
      'text/csv',
      'application/json',
      'text/xml',
      'application/xml'
    ];
    
    if (!supportedTypes.includes(file.type)) {
      console.error('Unsupported file type:', file.type);
      return NextResponse.json({ 
        error: `Unsupported file type: ${file.type}. Please upload screenshots, images, text files, or social media data exports.` 
      }, { status: 400 });
    }

    console.log('File validated successfully');

    // Handle text files differently - extract text content and send directly
    const isTextFile = file.type.startsWith('text/') || 
                      file.type === 'application/json' || 
                      file.type === 'application/xml';

    let analysis;
    
    if (isTextFile) {
      console.log('Processing as text file...');
      const textContent = await file.text();
      console.log('Text content extracted, length:', textContent.length);
      
      if (!textContent.trim()) {
        return NextResponse.json({ error: 'File appears to be empty' }, { status: 400 });
      }
      
      analysis = await generateSummaryFromText(textContent, file.name, summaryLength);
    } else {
      console.log('Processing as binary file (PDF/image)...');
      // Convert file to base64 for Google AI
      const arrayBuffer = await file.arrayBuffer();
      const base64Data = Buffer.from(arrayBuffer).toString('base64');
      console.log('File converted to base64, size:', base64Data.length);
      
      analysis = await generateSummaryFromFile(base64Data, file.type, file.name, summaryLength);
    }

    console.log('Analysis generated successfully');

    // Return response
    if (responseFormat === 'markdown') {
      const markdownResponse = `# Social Media Analysis: ${file.name}

## Analysis (${summaryLength})

${analysis}

## Content Information

- **File Name**: ${file.name}
- **File Type**: ${file.type}
- **File Size**: ${Math.round(file.size / 1024)} KB
- **Analysis Type**: ${summaryLength}

---
*Generated by Social Media Analyzer using Google Gemini AI*`;

      return new Response(markdownResponse, {
        headers: { 'Content-Type': 'text/markdown' }
      });
    } else {
      return NextResponse.json({
        success: true,
        analysis: analysis,
        fileName: file.name,
        fileSize: file.size,
        fileType: file.type,
        summaryLength: summaryLength
      });
    }

  } catch (error) {
    console.error('=== API Error ===');
    console.error('Error processing file:', error);
    console.error('Error stack:', error.stack);
    
    return NextResponse.json(
      { 
        error: 'Failed to process file', 
        details: error.message,
        stack: process.env.NODE_ENV === 'development' ? error.stack : undefined
      },
      { status: 500 }
    );
  }
}

async function generateSummaryFromText(textContent, fileName, summaryLength) {
  try {
    const apiKey = process.env.GOOGLE_GEMINI_API_KEY;
    
    if (!apiKey) {
      throw new Error('Google Gemini API key not configured');
    }

    const genAI = new GoogleGenerativeAI(apiKey);
    const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });

    // Create system prompts based on analysis depth
        const lengthPrompts = {
      short: `You are a social media content analyst. Analyze the following content and return ONLY a valid JSON object (no markdown, no backticks, no extra text) with this exact structure:
{
  "summary": "1-2 sentence summary of the main idea",
  "sentiment": "positive/negative/neutral/mixed",
  "themes": ["theme1", "theme2", "theme3"],
  "engagement_score": "low/medium/high",
  "engagement_reasoning": "Brief explanation of the engagement score"
}`,

      medium: `You are a social media content analyst. Analyze the following content and return ONLY a valid JSON object (no markdown, no backticks, no extra text) with this exact structure:
{
  "summary": "1 short paragraph summary of what the content is about",
  "sentiment": "positive/negative/neutral/mixed",
  "themes": ["theme1", "theme2", "theme3", "theme4", "theme5"],
  "engagement_score": "low/medium/high",
  "engagement_reasoning": "Detailed explanation of the engagement score",
  "improvement_suggestions": ["suggestion1", "suggestion2", "suggestion3"]
}`,

      long: `You are a social media content analyst. Analyze the following content and return ONLY a valid JSON object (no markdown, no backticks, no extra text) with this exact structure:
{
  "summary": "2-3 paragraph detailed summary of the content",
  "sentiment": "positive/negative/neutral/mixed",
  "sentiment_breakdown": "Detailed justification of the sentiment analysis",
  "themes": ["theme1", "theme2", "theme3", "theme4", "theme5", "theme6", "theme7"],
  "engagement_score": "low/medium/high",
  "engagement_reasoning": "Detailed analysis of virality, relatability, and shareability",
  "platform_strategy": {
    "twitter": "optimization suggestions for Twitter",
    "instagram": "optimization suggestions for Instagram", 
    "linkedin": "optimization suggestions for LinkedIn"
  }
}`
    };

    const systemPrompt = lengthPrompts[summaryLength] || lengthPrompts.medium;
    const fullPrompt = `${systemPrompt}\n\nSocial media content:\n\n${textContent}`;
    
    console.log('Sending text to Google AI for processing...');
    
    const result = await model.generateContent(fullPrompt);
    const response = result.response;
    const rawText = response.text();

    console.log('Google AI text processing completed successfully');

    // Try to parse JSON response - clean markdown formatting first
    try {
      // Remove markdown code blocks if present
      let cleanedText = rawText.trim();
      if (cleanedText.startsWith('```json')) {
        cleanedText = cleanedText.replace(/^```json\s*/, '').replace(/\s*```$/, '');
      } else if (cleanedText.startsWith('```')) {
        cleanedText = cleanedText.replace(/^```\s*/, '').replace(/\s*```$/, '');
      }
      
      const analysisData = JSON.parse(cleanedText);
      return analysisData;
    } catch (parseError) {
      console.log('Failed to parse JSON, returning raw text:', parseError.message);
      console.log('Raw text was:', rawText);
      // If JSON parsing fails, return the raw text in a structured format
      return {
        summary: rawText,
        sentiment: "unknown",
        themes: [],
        engagement_score: "unknown",
        engagement_reasoning: "Unable to parse structured response"
      };
    }
  } catch (error) {
    console.error('AI text analysis generation error:', error);
    console.error('Error details:', error.response?.data || error.message);
    throw new Error('Failed to generate text analysis: ' + error.message);
  }
}

async function generateSummaryFromFile(base64Data, mimeType, fileName, summaryLength) {
  try {
    const apiKey = process.env.GOOGLE_GEMINI_API_KEY;
    
    if (!apiKey) {
      throw new Error('Google Gemini API key not configured');
    }

    const genAI = new GoogleGenerativeAI(apiKey);
    const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" }); // Use gemini-1.5-flash for file processing

    // Create the file part for Google AI
    const filePart = {
      inlineData: {
        data: base64Data,
        mimeType: mimeType
      }
    };

    // Create system prompts based on analysis depth and file type
    const isImage = mimeType.startsWith('image/');
    const basePrompt = isImage 
      ? `Analyze this social media screenshot/image and extract insights about the content, engagement, and trends visible.`
      : `Analyze this social media data export or document and provide insights about social media trends and patterns.`;

    const lengthPrompts = {
      short: `You are a social media content analyst. ${basePrompt} Return ONLY a valid JSON object (no markdown, no backticks, no extra text) with this exact structure:
{
  "summary": "1-2 sentence summary of the main idea",
  "sentiment": "positive/negative/neutral/mixed",
  "themes": ["theme1", "theme2", "theme3"],
  "engagement_score": "low/medium/high",
  "engagement_reasoning": "Brief explanation of the engagement score"
}`,

      medium: `You are a social media content analyst. ${basePrompt} Return ONLY a valid JSON object (no markdown, no backticks, no extra text) with this exact structure:
{
  "summary": "1 short paragraph summary of what the content is about",
  "sentiment": "positive/negative/neutral/mixed",
  "themes": ["theme1", "theme2", "theme3", "theme4", "theme5"],
  "engagement_score": "low/medium/high",
  "engagement_reasoning": "Detailed explanation of the engagement score",
  "improvement_suggestions": ["suggestion1", "suggestion2", "suggestion3"]
}`,

      long: `You are a social media content analyst. ${basePrompt} Return ONLY a valid JSON object (no markdown, no backticks, no extra text) with this exact structure:
{
  "summary": "2-3 paragraph detailed summary of the content",
  "sentiment": "positive/negative/neutral/mixed",
  "sentiment_breakdown": "Detailed justification of the sentiment analysis",
  "themes": ["theme1", "theme2", "theme3", "theme4", "theme5", "theme6", "theme7"],
  "engagement_score": "low/medium/high",
  "engagement_reasoning": "Detailed analysis of virality, relatability, and shareability",
  "platform_strategy": {
    "twitter": "optimization suggestions for Twitter",
    "instagram": "optimization suggestions for Instagram", 
    "linkedin": "optimization suggestions for LinkedIn"
  }
}`
    };

    const systemPrompt = lengthPrompts[summaryLength] || lengthPrompts.medium;
    
    console.log('Sending file to Google AI for processing...');
    
    // Generate content with both text prompt and file
    const result = await model.generateContent([systemPrompt, filePart]);
    const response = result.response;
    const rawText = response.text();

    console.log('Google AI processing completed successfully');

    // Try to parse JSON response - clean markdown formatting first
    try {
      // Remove markdown code blocks if present
      let cleanedText = rawText.trim();
      if (cleanedText.startsWith('```json')) {
        cleanedText = cleanedText.replace(/^```json\s*/, '').replace(/\s*```$/, '');
      } else if (cleanedText.startsWith('```')) {
        cleanedText = cleanedText.replace(/^```\s*/, '').replace(/\s*```$/, '');
      }
      
      const analysisData = JSON.parse(cleanedText);
      return analysisData;
    } catch (parseError) {
      console.log('Failed to parse JSON, returning raw text:', parseError.message);
      console.log('Raw text was:', rawText);
      // If JSON parsing fails, return the raw text in a structured format
      return {
        summary: rawText,
        sentiment: "unknown",
        themes: [],
        engagement_score: "unknown",
        engagement_reasoning: "Unable to parse structured response"
      };
    }
  } catch (error) {
    console.error('AI analysis generation error:', error);
    console.error('Error details:', error.response?.data || error.message);
    throw new Error('Failed to generate analysis: ' + error.message);
  }
}
